- name: Build Android App
  # You may pin to the exact commit or the version.
  # uses: sparkfabrik/android-build-action@f92138ceac91a41b1d1a64b2c2bf3fb69ece85eb
  uses: sparkfabrik/android-build-action@v1.2.0
  with:
    # You can build an unsigned APK (assemble) or a signed AAB (bundle).
    build-type: # optional, default is assemble
    # Name of the gradle task to exec (eg. assembleDebug, assembleRelease, bundleRelease)
    gradle-task: # optional, default is assembleDebug
    # Increment build number
    increment-build-number: # optional
    # Package name
    package-name: # optional
    # Keystore file content as base64 encoded string
    keystore-content: # optional
    # Keystore password
    keystore-password: # optional
    # Keystore alias
    keystore-alias: # optional
    # JSON keystore file content
    json-key-data: # optional
    # Upload to Play Store
    upload-to-play-store: # optional
    # Project path
    project-path: 
    # Output path of the build
    output-path: # optional, default is output.apk
    # Boolean to tell the Action to upload the .ipa to Browserstack App Live after the build.
    browserstack-upload: # optional
    # Browserstack username (required if browserstack-upload == true)
    browserstack-username: # optional, default is 
    # Browserstack access key (required if browserstack-upload == true)
    browserstack-access-key: # optional, default is 
